version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  app:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_LIFETIME: ${ACCESS_LIFETIME}
      REFRESH_LIFETIME: ${REFRESH_LIFETIME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT_NUMBER: ${REDIS_PORT_NUMBER}
    links:
      - db
      - redis
    ports:
      - "6000:6000"
    volumes:
      - ./src:/app/src

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

  redis:
    image: redis
    ports:
      - "6379:6379"